<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Shop Page</h1>
    <p>This is the shopping cart page.</p>
    <a href="index.php">Continue Shopping</a>
    <!-- Products -->
<br>
<?php print_r($_SESSION['cart'] ?? []); ?>
<br>
<?php
    foreach($_SESSION['cart'] as $producto){
        echo '<p>'.$producto->getName().'</p>';
    }

?>
    <input type="submit" value="Pay" name="Pay">

</body>
</html>