<link rel="stylesheet" href="public/styles/style_cart.css">

<h1>Shopping Cart</h1>
<p>This is your shopping cart page.</p>

<div class="cart-container">
    <?php if(!empty($_SESSION['cart'])): ?>
        <?php foreach($_SESSION['cart'] as $product): ?>
            <div class="cart-item">
                <div class="product-name">
                    <?php echo htmlspecialchars($product->getName()); ?>
                </div>
                <div class="product-info">
                    <span>Qty: <?php echo $product->quantity; ?></span> |
                    <span><?php echo number_format($product->getPrice() * $product->quantity, 2); ?> €</span>
                    <span>
                        <form action="index.php?c=cart&action=remove&product_id=<?php echo $product->getId(); ?>" method="post" class="remove-form">
                            <input type="submit" value="Remove" class="remove-button">
                        </form>
                    </span>
                </div>
            </div>
            <?php endforeach; ?>
            <form action="index.php?c=cart&action=clear" method="post" class="clear-cart-form">
                <input type="submit" value="Clear Cart" class="clear-cart-button">
            </form>
            <form action="index.php?c=cart&action=pay" method="post">
                <input type="submit" value="Pay" name="Pay" class="pay-button">
            </form>
            <?php else: ?>
                <p class="cart-empty">Your cart is empty.</p>
                <?php endif; ?>
    <a href="index.php" class="continue-shopping">Continue Shopping</a>
</div>
