<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="public/styles/style_login.css">
</head>
<body class="login-page">
  <div class="login-container">
    <h1>LOGIN</h1>

    <?php
      if(isset($_SESSION['message'])){
          $colorClass = $_SESSION['message_type'] == 'success' ? 'green' : 'red';
          echo "<p class='message $colorClass'>" . $_SESSION['message'] . "</p>";
          unset($_SESSION['message']);
          unset($_SESSION['message_type']);
      }
    ?>

    <form action="index.php?c=login" method="post" class="login-form">
        <label for="username">Usuario:</label>
        <input type="text" id="username" name="username" required>

        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required>

        <div class="button-group">
          <input type="submit" value="Login" name="Login">
          <input type="submit" value="Registrar" name="Registrar">
        </div>
    </form>

    <a href="index.php" class="back-link">Volver</a>
  </div>
</body>

</html>
