<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>  
    <h1>LOGIN</h1>
    
    <?php
        if(isset($_SESSION['message'])){
            $color = $_SESSION['message_type'] == 'success' ? 'green' : 'red';
            echo "<p style='color: $color;'>" . $_SESSION['message'] . "</p>";
            // Limpiar el mensaje después de mostrarlo
            unset($_SESSION['message']);
            unset($_SESSION['message_type']);
        }
    ?>
    
    <form action="index.php?c=login" method="post">
        <label for="username">Usuario:</label>
        <input type="text" id="username" name="username" required>
        <br>
        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <input type="submit" value="Login" name="Login">
        <input type="submit" value="Registrar" name="Registrar">
    </form>
    <a href='index.php'>Volver</a>
</body>
</html>
