<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

<?php

if (!$pedidos){
    ?><h4> NO HAY PEDIDOS </h4><?php
}else{
    foreach($pedidos as $pedido){
        
        ?>  
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>TOTAL</th>
                <th>STATE</th>
                <th>DATE</th>
            </tr>
        </thead>    
        <tbody>
            <tr>
                <td><?= htmlspecialchars($pedido->getId()) ?></td>
                <td><?= htmlspecialchars($pedido->getTotal()) ?></td>
                <td><?= htmlspecialchars($pedido->getStatus()) ?></td>
                <td><?= htmlspecialchars($pedido->getOrder_Date()) ?></td>
            </tr>
        </tbody>
    </table>
    <?php
    }
}
?>
<a href="index.php">← Back to shop</a>
</body>
</html>


